name: Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      pypi_environment:
        description: 'PyPI environment to publish to'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - 'testpypi'

permissions:
    id-token: write
    contents: read

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install UV
      uses: astral-sh/setup-uv@v3

    - name: Install build dependencies
      run: |
        uv sync --dev

    - name: Build package
      run: |
        uv run python -m build

    - name: Check package metadata
      run: |
        uv add --dev twine
        uv run twine check dist/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  publish-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: testpypi
      url: https://test.pypi.org/p/nwws-oi-receiver

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true